haxelib install openfl 9.4.2
haxelib install lime 8.1.0
haxelib install flixel 5.5.0
haxelib install flixel-addons 3.2.0
haxelib install flixel-ui 2.5.0
haxelib install hscript 2.6.0
haxelib install hxCodec 2.5.1
haxelib install hxcpp 4.2.1
haxelib install hxdiscord_rpc 1.3.0
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git